#!/usr/bin/env python3
# -*- mode:python -*-


if __name__ == '__main__':
    import pathlib
    import importlib.machinery
    import sys

    root = pathlib.Path(__file__).absolute().parent
    assert root.exists()
    assert (root/"gitfat").exists()
    assert (root/"gitfat").is_dir()

    import importlib.machinery

    gitfat = importlib.machinery.SourceFileLoader('gitfat',str(root/"gitfat"/"__init__.py")).load_module()
    gitfat.main(sys.argv)
